### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by gert76** [aherve/typescript-express-docker#1]
Hi

I get the following when I run "docker-compose up"

![image](https://cloud.githubusercontent.com/assets/1830047/19660176/09a8e8c2-9a2f-11e6-8e05-228c82323d9d.png)

**Comment by qqilihq** [comment]
Same here.

**Comment by stephengardner** [comment]
Same here.

**Comment by aherve** [comment]
This was due to the fact that the api were looking for the transpiled file before it was created. I've updated the code so this is now fixed, along with other issues.
